swagger: "2.0"
basePath: /api
schemes: 
  - http
  - https
produces: 
  - "application/json"
info: 
  version: "3.0.0-alpha1"
  title: "Boodskap API"
  description: "Boodskap IoT Platform API"
  termsOfService: "https://boodskap.io/terms-conditions"
  contact: 
    name: "Boodskap Team"
  license: 
    name: "MIT"
paths:
  '/java/{type}/pkg/list/{loader}':
    get:
      tags:
        - List Packages
      summary: List Packages
      operationId: listPackages
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: type
          in: path
          description: Type ** [ java || groovy ] **
          required: true
          type: string
        - name: loader
          in: path
          description: Filter by loader id
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
        - name: page
          in: query
          description: Page index, starts from 0
          required: false
          type: integer
          format: int32
        - name: pageSize
          in: query
          description: Maximum number of assets to be listed
          required: false
          type: integer
          format: int32
        - name: global
          in: query
          description: True for system groovy classes
          required: false
          type: boolean
        - name: next
          in: query
          description: If next page
          required: false
          type: boolean
        - name: fileName
          in: query
          description: Last file name of the previous list operation, **required** if **next** is true
          required: false
          type: string
        - name: pkg
          in: query
          description: Last pkg name of the previous list operation, **required** if **next** is true
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              type: string
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/java/{type}/class/list/{loader}':
    get:
      tags:
        - List Classes
      summary: List Classes
      operationId: listClasses
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: type
          in: path
          description: Type ** [ java || groovy ] **
          required: true
          type: string
        - name: loader
          in: path
          description: Filter by loader id
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
        - name: page
          in: query
          description: Page index, starts from 0
          required: false
          type: integer
          format: int32
        - name: pageSize
          in: query
          description: Maximum number of assets to be listed
          required: false
          type: integer
          format: int32
        - name: global
          in: query
          description: True for system groovy classes
          required: false
          type: boolean
        - name: next
          in: query
          description: If next page
          required: false
          type: boolean
        - name: fileName
          in: query
          description: Last file name of the previous list operation, **required** if **next** is true
          required: false
          type: string
        - name: pkg
          in: query
          description: Last package name of the previous list operation, **required** if **next** is true
          required: false
          type: string
        - name: name
          in: query
          description: Last class name of the previous list operation, **required** if **next** is true
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/JavaClass'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/java/{type}/class/list/{loader}/{pkg}':
    get:
      tags:
        - List Package Classes
      summary: List Package Classes
      operationId: listPackageClasses
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: type
          in: path
          description: Type ** [ java || groovy ] **
          required: true
          type: string
        - name: loader
          in: path
          description: Filter by loader id
          required: true
          type: string
        - name: pkg
          in: path
          description: Filter by package name
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
        - name: page
          in: query
          description: Page index, starts from 0
          required: false
          type: integer
          format: int32
        - name: pageSize
          in: query
          description: Maximum number of assets to be listed
          required: false
          type: integer
          format: int32
        - name: global
          in: query
          description: True for system groovy classes
          required: false
          type: boolean
        - name: next
          in: query
          description: If next page
          required: false
          type: boolean
        - name: fileName
          in: query
          description: Last file name of the previous list operation, **required** if **next** is true
          required: false
          type: string
        - name: name
          in: query
          description: Last class name of the previous list operation, **required** if **next** is true
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/JavaClass'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/java/{type}/class/search':
    post:
      tags:
        - Search Classes
      summary: Search Classes
      operationId: searchClasses
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: type
          in: path
          description: Type ** [ java || groovy ] **
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
        - name: pageSize
          in: query
          description: Maximum number of objects to be listed
          required: false
          type: integer
          format: int32
        - name: global
          in: query
          description: True for system classes
          required: false
          type: boolean
        - name: query
          in: body
          description: Search string
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/JavaClass'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/java/{type}/class/count':
    get:
      tags:
        - Count All Classes
      summary: Count All Classes
      operationId: countAllClasses
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: type
          in: path
          description: Type ** [ java || groovy ] **
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Another domain Key, optional (admin access)
          required: false
          type: string
        - name: global
          in: query
          description: Is global loader classes
          required: false
          type: boolean
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Count"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/java/{type}/class/count/{loader}':
    get:
      tags:
        - Count Loader Classes
      summary: Count Loader Classes
      operationId: countLoaderClasses
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: type
          in: path
          description: Type ** [ java || groovy ] **
          required: true
          type: string
        - name: loader
          in: path
          description: Filter by loader id
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Another domain Key, optional (admin access)
          required: false
          type: string
        - name: global
          in: query
          description: Is global loader classes
          required: false
          type: boolean
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Count"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/java/{type}/class/count/{loader}/{pkg}':
    get:
      tags:
        - Count Loader Package Classes
      summary: Count Loader Package Classes
      operationId: countLoaderPackageClasses
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: type
          in: path
          description: Type ** [ java || groovy ] **
          required: true
          type: string
        - name: loader
          in: path
          description: Filter by loader id
          required: true
          type: string
        - name: pkg
          in: path
          description: Filter by package name
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Another domain Key, optional (admin access)
          required: false
          type: string
        - name: global
          in: query
          description: Is global loader classes
          required: false
          type: boolean
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Count"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
definitions:
  ApiError: 
    type: "object"
    required: 
      - "code"
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
  Count:
    type: object
    required:
      - total
    properties:
      total:
        type: integer
        format: int64
  JavaClass:
    type: object
    discriminator: javaClassType
    required:
    - pkg
    - name
    properties:
      pkg:
        type: string
      name:
        type: string
      loader:
        type: string
        
  Success: 
    type: "object"
    required:
      - code
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
