swagger: "2.0"
basePath: /api
schemes: 
  - http
  - https
produces: 
  - "application/json"
info: 
  version: "3.0.0-alpha1"
  title: "Boodskap API"
  description: "Boodskap IoT Platform API"
  termsOfService: "https://boodskap.io/terms-conditions"
  contact: 
    name: "Boodskap Team"
  license: 
    name: "MIT"
paths:
  '/rspec/create':
    post:
      tags:
        - Create Record Definition
      summary: Create Record Definition
      operationId: createRecordDefinition
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: entity
          in: body
          description: RecordSpecification JSON object
          required: true
          schema:
            $ref: '#/definitions/RecordSpecification'
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/rspec/get/{specId}':
    get:
      tags:
        - Get Record Definition
      summary: Retreive Record Definition
      operationId: getRecordDefinition
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: specId
          in: path
          description: Record Spec id
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/RecordSpecification'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/rspec/delete':
    delete:
      tags:
        - Delete All Record Definitions
      summary: Delete All Record Definitions
      operationId: deleteAllRecordDefinitions
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/rspec/delete/{specId}':
    delete:
      tags:
        - Delete Record Definition
      summary: Delete Record Definition
      operationId: deleteRecordDefinition
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: specId
          in: path
          description: Record Spec id
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/rspec/list':
    get:
      tags:
        - List Record Definitions
      summary: List Record Definition
      operationId: listRecordDefinitions
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: page
          in: query
          description: Page index, starts from 0
          required: false
          type: integer
          format: int32
        - name: pageSize
          in: query
          description: Maximum number of objects to be listed
          required: false
          type: integer
          format: int32
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
        - name: next
          in: query
          description: If next is true, **eid** is required
          required: false
          type: boolean
        - name: specId
          in: query
          description: Last Record Definition Id of the previous list operation, **required** if **next** is true
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/RecordSpecification'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/rspec/countall':
    get:
      tags:
        - Count All Record Definition
      summary: Count All Record Definition
      operationId: countAllRecordDefinitions
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in admin user
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Count"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/rspec/count':
    get:
      tags:
        - Count Domain Record Definitions
      summary: Count Domain Record Definitions
      operationId: countDomainRecordDefinitions
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Count"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/rspec/create/field/{specId}':
    post:
      tags:
        - Create Record Field
      summary: Create Record Field
      operationId: createRecordField
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: specId
          in: path
          description: Record Spec id
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
        - name: entity
          in: body
          description: RecordField JSON object
          required: true
          schema:
            $ref: '#/definitions/RecordField'
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/RecordSpecification"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/rspec/modify/field/{specId}':
    post:
      tags:
        - Modify Record Field
      summary: Modify Record Field
      operationId: modifyRecordField
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: specId
          in: path
          description: Record Spec id
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
        - name: entity
          in: body
          description: RecordField JSON object
          required: true
          schema:
            $ref: '#/definitions/RecordField'
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/RecordSpecification"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/rspec/remove/field/{specId}/{name}':
    delete:
      tags:
        - Delete Record Field
      summary: Delete Record Field
      operationId: deleteRecordField
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: specId
          in: path
          description: Record Spec id
          required: true
          type: string
        - name: name
          in: path
          description: Field Name
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/rspec/count/fields/{specId}':
    get:
      tags:
        - Count Record Definition Fields
      summary: Count Record Definition Fields
      operationId: countRecordDefinitionFields
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: specId
          in: path
          description: Record Spec id
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in admin user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Count"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
definitions:
  ApiError: 
    type: "object"
    required: 
      - "code"
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
  Count:
    type: object
    required:
      - total
    properties:
      total:
        type: integer
        format: int64
  RecordField:
    type: object
    required:
      - name
      - dataType
    properties:
      domainKey:
        type: string
      specId:
        type: string
      name:
        type: string
      dataType:
        type: string
        enum:
         - BOOLEAN
         - BYTE
         - CHAR
         - SHORT
         - INT
         - LONG
         - FLOAT
         - DOUBLE
         - STRING
         - UUID
         - BLOB
         - JSON
      description:
        type: string
      indexed:
        type: boolean
      fulltextIndexed:
        type: boolean
  RecordSpecification:
    type: object
    required:
      - specId
      - name
      - fields
    properties:
      domainKey:
        type: string
      specId:
        type: string
      name:
        type: string
      description:
        type: string
      fields:
        type: array
        items:
          $ref: '#/definitions/RecordField'
      createdStamp:
        type: integer
        format: int64
      updatedStamp:
        type: integer
        format: int64
  Success: 
    type: "object"
    required:
      - code
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
