swagger: "2.0"
basePath: /api
schemes: 
  - http
  - https
produces: 
  - "application/json"
info: 
  version: "3.0.0-alpha1"
  title: "Boodskap API"
  description: "Boodskap IoT Platform API"
  termsOfService: "https://boodskap.io/terms-conditions"
  contact: 
    name: "Boodskap Team"
  license: 
    name: "MIT"
paths:
  '/billing/schedule/upsert':
    post:
      tags:
        - Upsert Billing Schedule
      summary: Create / Update Billing Schedule
      operationId: upsertBillingSchedule
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dto
          in: body
          description: BillingSchedule JSON object
          required: true
          schema:
            $ref: '#/definitions/BillingSchedule'
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/IDResult"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/billing/schedule/delete/{targetDomain}/{scheduleId}':
    delete:
      tags:
        - Delete Billing Schedule
      summary: Delete Billing Schedule
      operationId: deleteBillingSchedule
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: targetDomain
          in: path
          required: true
          type: string
        - name: scheduleId
          in: path
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/billing/schedule/clear/{targetDomain}':
    delete:
      tags:
        - Delete All Billing Schedules
      summary: Delete All Billing Schedules
      operationId: deleteBillingSchedules
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: targetDomain
          in: path
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/billing/contact/upsert':
    post:
      tags:
        - Upsert Billing Contact
      summary: Create / Update Billing Contact
      operationId: upsertBillingContact
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dto
          in: body
          description: BillingContact JSON object
          required: true
          schema:
            $ref: '#/definitions/BillingContact'
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/IDResult"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/billing/contact/delete/{targetDomain}/{contactId}':
    delete:
      tags:
        - Delete Billing Contact
      summary: Delete Billing Contact
      operationId: deleteBillingContact
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: targetDomain
          in: path
          required: true
          type: string
        - name: contactId
          in: path
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/billing/contact/clear/{targetDomain}':
    delete:
      tags:
        - Delete All Billing Contacts
      summary: Delete All Billing Contacts
      operationId: deleteBillingContacts
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: targetDomain
          in: path
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/billing/invoice/upsert':
    post:
      tags:
        - Upsert Billing Invoice
      summary: Create / Update Billing Invoice
      operationId: upsertBillingInvoice
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dto
          in: body
          description: BillingInvoice JSON object
          required: true
          schema:
            $ref: '#/definitions/BillingInvoice'
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/IDResult"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/billing/invoice/delete/{targetDomain}/{invoiceId}':
    delete:
      tags:
        - Delete Billing Invoice
      summary: Delete Billing Invoice
      operationId: deleteBillingInvoice
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: targetDomain
          in: path
          required: true
          type: string
        - name: invoiceId
          in: path
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/billing/invoice/clear/{targetDomain}':
    delete:
      tags:
        - Delete All Billing Invoices
      summary: Delete All Billing Invoices
      operationId: deleteBillingInvoices
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: targetDomain
          in: path
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/billing/template/upsert':
    post:
      tags:
        - Upsert Billing Template
      summary: Create / Update Billing Template
      operationId: upsertBillingTemplate
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dto
          in: body
          description: BillingTemplate JSON object
          required: true
          schema:
            $ref: '#/definitions/BillingTemplate'
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/billing/template/delete/item/{name}/{item}':
    delete:
      tags:
        - Delete Billing Template Item
      summary: Delete Billing Template Item
      operationId: deleteBillingTemplateItem
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: name
          in: path
          required: true
          type: string
        - name: item
          in: path
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/billing/template/clear/items/{name}':
    delete:
      tags:
        - Delete Billing Template Items
      summary: Delete Billing Template Items
      operationId: deleteBillingTemplateItems
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: name
          in: path
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/billing/template/clear':
    delete:
      tags:
        - Delete All Billing Templates
      summary: Delete All Billing Templates
      operationId: deleteAllBillingTemplates
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
definitions:
  ApiError: 
    type: "object"
    required: 
      - "code"
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
  BillingContact:
    type: object
    properties:
      domainKey:
        type: string
      targetDomain:
        type: string
      contactId:
        type: string
        format: uuid
      type:
        type: string
      name:
        type: string
      email:
        type: string
      contact:
        type: string
      address:
        type: string
      city:
        type: string
      state:
        type: string
      country:
        type: string
      zipcode:
        type: string
      logo:
        type: string
      updatedtime:
        type: integer
        format: int64
      createdtime:
        type: integer
        format: int64
      obj:
        type: string
      department:
        type: string
      description:
        type: string
  BillingInvoice:
    type: object
    properties:
      domainKey:
        type: string
      targetDomain:
        type: string
      invoiceId:
        type: string
        format: uuid
      invoicename:
        type: string
      invoiceno:
        type: string
      frequency:
        type: string
      file:
        type: string
      grandtotal:
        type: number
        format: double
      startdate:
        type: integer
        format: int64
      enddate:
        type: integer
        format: int64
      createdtime:
        type: integer
        format: int64
      obj:
        type: string
      invoicetype:
        type: string
  BillingSchedule:
    type: object
    properties:
      domainKey:
        type: string
      targetDomain:
        type: string
      scheduleId:
        type: string
        format: uuid
      invoicename:
        type: string
      invoicecode:
        type: string
      frequency:
        type: string
      currency:
        type: string
      companyname:
        type: string
      payername:
        type: string
      updatedtime:
        type: integer
        format: int64
      createdtime:
        type: integer
        format: int64
      discounteditems:
        type: boolean
      enabled:
        type: boolean
      obj:
        type: string
      startdate:
        type: integer
        format: int64
      enddate:
        type: integer
        format: int64
      startevery:
        type: string
      weekday:
        type: integer
        format: int32
      billingtype:
        type: string
      executed:
        type: boolean
  BillingTemplate:
    type: object
    properties:
      domainKey:
        type: string
      templatename:
        type: string
      itemname:
        type: string
      description:
        type: string
      unitprice:
        type: number
        format: double
      tax:
        type: number
        format: float
      templatecode:
        type: string
      updatedtime:
        type: integer
        format: int64
      createdtime:
        type: integer
        format: int64
  IDResult:
    type: object
    required:
      - id
    properties:
      id:
        type: string
  Success: 
    type: "object"
    required:
      - code
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
