swagger: "2.0"
basePath: /api
schemes: 
  - http
  - https
produces: 
  - "application/json"
info: 
  version: "3.0.0-alpha1"
  title: "Boodskap API"
  description: "Boodskap IoT Platform API"
  termsOfService: "https://boodskap.io/terms-conditions"
  contact: 
    name: "Boodskap Team"
  license: 
    name: "MIT"
paths:
  '/asset/group/upsert':
    post:
      tags:
        - Create / Update Asset Group
      summary: Create / Update Asset Group
      operationId: upsertAssetGroup
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: entity
          in: body
          description: AssetGroup JSON object
          required: true
          schema:
            $ref: '#/definitions/AssetGroup'
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/asset/group/get/{oaid}/{gid}':
    get:
      tags:
        - Retreive Asset Group
      summary: Retreive Asset Group
      operationId: getAssetGroup
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: oaid
          in: path
          description: Owner Asset ID
          required: true
          type: string
        - name: gid
          in: path
          description: Group ID
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/AssetGroup'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/asset/group/count':
    post:
      tags:
        - Count All Asset Groups
      summary: Count All Asset Groups
      operationId: countAllAssetGroups
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Count"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/asset/group/remove':
    delete:
      tags:
        - Delete All Asset Groups
      summary: Delete All Asset Groups
      operationId: deleteAllAssetGroups
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in admin user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Success'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/asset/group/remove/{oaid}':
    delete:
      tags:
        - Delete Asset Groups
      summary: Delete Asset Groups
      operationId: deleteAssetGroups
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: oaid
          in: path
          description: Owner Asset ID
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Success'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/asset/group/remove/{oaid}/{gid}':
    delete:
      tags:
        - Delete Asset Group
      summary: Delete Asset Group
      operationId: deleteAssetGroup
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: oaid
          in: path
          description: Owner Asset ID
          required: true
          type: string
        - name: gid
          in: path
          description: Group ID
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Success'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/asset/group/list/{oaid}':
    get:
      tags:
        - List Asset Groups
      summary: List Asset Groups
      operationId: listAssetGroups
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: oaid
          in: path
          description: Owner Asset ID
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
        - name: page
          in: query
          description: Page index, starts from 0
          required: false
          type: integer
          format: int32
        - name: pageSize
          in: query
          description: Maximum number of assets to be listed
          required: false
          type: integer
          format: int32
        - name: next
          in: query
          description: If next is true, **eid** is required
          required: false
          type: boolean
        - name: gid
          in: query
          description: Last Group Id of the previous list operation, **required** if **next** is true
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/AssetGroup'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/asset/group/search':
    post:
      tags:
        - Search Asset Groups
      summary: Search Asset Groups
      operationId: searchAssetGroups
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
        - name: pageSize
          in: query
          description: Maximum number of objects to be listed
          required: false
          type: integer
          format: int32
        - name: query
          in: body
          description: Search string
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/AssetGroup'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
definitions:
  ApiError: 
    type: "object"
    required: 
      - "code"
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
  AssetGroup:
    type: object
    required:
      - ownerAssetId
      - groupId
    properties:
      ownerAssetId:
        type: string
      groupId:
        type: string
      domainKey:
        type: string
      name:
        type: string
      description:
        type: string
      groupEmail:
        type: string
      groupPhone:
        type: string
      createdStamp:
        type: integer
        format: int64
      individualBroadcast:
        type: boolean
      updatedStamp:
        type: integer
        format: int64
  Count:
    type: object
    required:
      - total
    properties:
      total:
        type: integer
        format: int64
  DomainObject:
    type: object
    discriminator: domainObjectType
    properties:
      domainKey:
        type: string
  Property:
    allOf:
    - $ref: '#/definitions/SystemProperty'
    - $ref: '#/definitions/DomainObject'
    - type: object
      discriminator: propertyType
  Storable:
    type: object
    discriminator: storableType
    properties:
      dataFormat:
        type: string
        description: Required if **dataType** is **blob**
        enum:
          - AS_IS
          - JSON
          - HEX
          - BASE64
      description:
        type: string
  Success: 
    type: "object"
    required:
      - code
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
  SystemProperty:
    allOf:
    - $ref: '#/definitions/Storable'
    - type: object
      discriminator: systemPropertyType
      properties:
        name:
          type: string
        value:
          type: string
        createdStamp:
          type: integer
          format: int64
        updatedStamp:
          type: integer
          format: int64
