swagger: "2.0"
basePath: /api
schemes: 
  - http
  - https
produces: 
  - "application/json"
info: 
  version: "3.0.0-alpha1"
  title: "Boodskap API"
  description: "Boodskap IoT Platform API"
  termsOfService: "https://boodskap.io/terms-conditions"
  contact: 
    name: "Boodskap Team"
  license: 
    name: "MIT"
paths:
  '/groovy/script/compile':
    post:
      tags:
        - Compile Groovy Script
      summary: Compile Groovy Script
      operationId: compileGroovyScript
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Another domain Key, optional (admin access)
          required: false
          type: string
        - name: loader
          in: query
          description: Optional class loader id
          required: false
          type: string
        - name: globalLoader
          in: query
          description: Optional global class loader id
          required: false
          type: string
        - name: script
          in: body
          description: TextContent JSON object
          required: true
          schema:
            $ref: '#/definitions/TextContent'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/GroovyClass'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/groovy/file/compile':
    post:
      tags:
        - Compile Groovy File
      summary: Compile Groovy File
      operationId: compileGroovyFile
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Another domain Key, optional (admin access)
          required: false
          type: string
        - name: loader
          in: query
          description: Optional class loader id
          required: false
          type: string
        - name: globalLoader
          in: query
          description: Optional global class loader id
          required: false
          type: string
        - name: script
          in: formData
          description: Groovy script file
          type: file
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/GroovyClass'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/groovy/content/upload':
    post:
      tags:
        - Upload Groovy Script
      summary: Upload Groovy Script
      operationId: uploadGroovyScript
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Another domain Key, optional (admin access)
          required: false
          type: string
        - name: loader
          in: query
          description: Optional class loader id
          required: false
          type: string
        - name: globalLoader
          in: query
          description: Optional global class loader id
          required: false
          type: string
        - name: global
          in: query
          description: Global script visible to all domains (admin access)
          required: false
          type: boolean
        - name: script
          in: body
          description: TextContent JSON object
          required: true
          schema:
            $ref: '#/definitions/TextContent'
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/GroovyClass'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/groovy/file/upload':
    post:
      tags:
        - Upload Groovy Script File
      summary: Upload Groovy Script File
      operationId: uploadGroovyScriptFile
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Another domain Key, optional (admin access)
          required: false
          type: string
        - name: loader
          in: query
          description: Optional class loader id
          required: false
          type: string
        - name: globalLoader
          in: query
          description: Optional global class loader id
          required: false
          type: string
        - name: global
          in: query
          description: Global script visible to all domains (admin access)
          required: false
          type: boolean
        - name: script
          in: formData
          description: Groovy script file
          type: file
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/GroovyClass'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/groovy/file/get/{loader}/{pkg}/{name}':
    get:
      tags:
        - Get Groovy Script File
      summary: Get Groovy Script File
      operationId: getGroovyScriptFile
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: loader
          in: path
          description: Class loader id
          required: true
          type: string
        - name: pkg
          in: path
          description: Package name
          required: true
          type: string
        - name: name
          in: path
          description: Class Name
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Another domain Key, optional (admin access)
          required: false
          type: string
        - name: global
          in: query
          description: Is global script (admin access)
          required: false
          type: boolean
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/GroovyClass"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/groovy/file/delete/{loader}/{pkg}/{name}':
    delete:
      tags:
        - Delete Groovy Script File
      summary: Delete Groovy Script File
      operationId: deleteGroovyScriptFile
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: loader
          in: path
          description: Class loader id
          required: true
          type: string
        - name: pkg
          in: path
          description: Package name
          required: true
          type: string
        - name: name
          in: path
          description: Class Name
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Another domain Key, optional (admin access)
          required: false
          type: string
        - name: global
          in: query
          description: Is global script (admin access)
          required: false
          type: boolean
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/groovy/file/delete/{loader}/{pkg}':
    delete:
      tags:
        - Delete Groovy Package
      summary: Delete Groovy Package
      operationId: deleteGroovyPackage
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: loader
          in: path
          description: Class loader id
          required: true
          type: string
        - name: pkg
          in: path
          description: Package name
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Another domain Key, optional (admin access)
          required: false
          type: string
        - name: global
          in: query
          description: Is global script (admin access)
          required: false
          type: boolean
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
definitions:
  ApiError: 
    type: "object"
    required: 
      - "code"
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
  Count:
    type: object
    required:
      - total
    properties:
      total:
        type: integer
        format: int64
  GroovyClass:
    allOf:
    - $ref: '#/definitions/JavaClass'
    - type: object
      properties:
        code:
          type: string
  JavaClass:
    type: object
    required:
      - pkg
      - name
    properties:
      pkg:
        type: string
      name:
        type: string
      loader:
        type: string
        
  Success: 
    type: "object"
    required:
      - code
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
  TextContent:
    type: object
    required:
      - content
    properties:
      content:
        type: string
