swagger: "2.0"
basePath: /api
schemes: 
  - http
  - https
produces: 
  - "application/json"
info: 
  version: "3.0.0-alpha1"
  title: "Boodskap API"
  description: "Boodskap IoT Platform API"
  termsOfService: "https://boodskap.io/terms-conditions"
  contact: 
    name: "Boodskap Team"
  license: 
    name: "MIT"
paths:
  '/alexa/upsert':
    post:
      tags:
        - Upsert Alexa
      summary: Create / Update Alexa
      operationId: upsertAlexa
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dto
          in: body
          description: Alexa JSON object
          required: true
          schema:
            $ref: '#/definitions/Alexa'
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/IDResult"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/alexa/get/{alexaId}':
    get:
      tags:
        - Get Alexa
      summary: Retrieve Alexa
      operationId: getAlexa
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: alexaId
          in: path
          description: Alexa Id
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Alexa'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/alexa/countall':
    get:
      tags:
        - Count All Alexa
      summary: Count All Alexa
      operationId: countAllAlexa
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Count"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/alexa/count':
    get:
      tags:
        - Count All Domain Alexa
      summary: Count All Domain Alexa
      operationId: countAllDomainAlexa
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Count"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/alexa/list':
    get:
      tags:
        - List Alexa
      summary: List Alexa
      operationId: listAlexa
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: page
          in: query
          description: Page index, starts from 0
          required: false
          type: integer
          format: int32
        - name: pageSize
          in: query
          description: Maximum number of objects to be listed
          required: false
          type: integer
          format: int32
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
        - name: next
          in: query
          description: If next is true, **eid** is required
          required: false
          type: boolean
        - name: eid
          in: query
          description: Last Alexa Id of the previous list operation, **required** if **next** is true
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Alexa'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/alexa/search':
    post:
      tags:
        - Search Alexa
      summary: Search Alexa
      operationId: searchAlexa
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: pageSize
          in: query
          description: Maximum number of objects to be listed
          required: false
          type: integer
          format: int32
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
        - name: query
          in: body
          description: Search string
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Alexa'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/alexa/delete/{alexaId}':
    delete:
      tags:
        - Delete Alexa
      summary: Delete Alexa
      operationId: deleteAlexa
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: alexaId
          in: path
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/alexa/deleteall':
    delete:
      tags:
        - Delete all Alexa
      summary: Delete all Alexa
      operationId: deleteAllAlexa
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
definitions:
  Alexa:
    type: object
    required:
      - alexaId
    properties:
      alexaId:
        type: string
      domainKey:
        type: string
      ruleType:
        type: string
      ruleName:
        type: string
      intentName:
        type: string
      errorResponse:
        type: string
      createdBy:
        type: string
      registeredStamp:
        type: integer
        format: int64
      updatedStamp:
        type: integer
        format: int64
  ApiError: 
    type: "object"
    required: 
      - "code"
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
  Count:
    type: object
    required:
      - total
    properties:
      total:
        type: integer
        format: int64
  IDResult:
    type: object
    required:
      - id
    properties:
      id:
        type: string
  Success: 
    type: "object"
    required:
      - code
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
