swagger: "2.0"
basePath: /api
schemes: 
  - http
  - https
produces: 
  - "application/json"
info: 
  version: "3.0.0-alpha1"
  title: "Boodskap API"
  description: "Boodskap IoT Platform API"
  termsOfService: "https://boodskap.io/terms-conditions"
  contact: 
    name: "Boodskap Team"
  license: 
    name: "MIT"
paths:
  '/push/message':
    post:
      tags:
        - Push Message
      summary: Push New Message
      operationId: pushMessage
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: entity
          in: body
          description: Message JSON object
          required: true
          schema:
            $ref: '#/definitions/PushMessage'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/PushResult'
  '/push/raw/{mid}':
    post:
      tags:
        - Push Raw Message
      summary: Push Raw Message
      operationId: pushRawMessage
      consumes:
        - "text/plain"
      produces:
        - "application/json"
      parameters:
        - name: mid
          in: path
          description: Message ID (defined through message spec)
          required: true
          type: string
        - name: key
          in: query
          description: Domain key
          required: true
          type: string
        - name: api
          in: query
          description: API key or Device password
          required: true
          type: string
        - name: did
          in: query
          description: Device ID
          required: true
          type: string
        - name: dmdl
          in: query
          description: Device model
          required: false
          type: string
        - name: fwver
          in: query
          description: Device firmware version
          required: false
          type: string
        - name: data
          in: body
          description: Message payload JSON object
          required: true
          schema:
            type: object
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/PushResult'
  '/push/bin/file/{type}':
    post:
      tags:
        - Push Binary File
      summary: Push Binary File
      operationId: pushBinaryFile
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: type
          in: path
          description: binary type (binary rule)
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain key
          required: true
          type: string
        - name: akey
          in: query
          description: API key
          required: true
          type: string
        - name: did
          in: query
          description: Device ID
          required: true
          type: string
        - name: dmdl
          in: query
          description: Device model
          required: false
          type: string
        - name: fwver
          in: query
          description: Device firmware version
          required: false
          type: string
        - name: properties
          in: query
          description: extra properties for decoding
          type: string
          required: false
        - name: binfile
          in: formData
          description: Binary file content
          type: file
          required: true
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/PushResult"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/push/bin/data/{type}':
    post:
      tags:
        - Push Binary Data
      summary: Push Binary Data
      operationId: pushBinaryData
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: type
          in: path
          description: binary type (binary rule)
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain key
          required: true
          type: string
        - name: akey
          in: query
          description: API key
          required: true
          type: string
        - name: did
          in: query
          description: Device ID
          required: true
          type: string
        - name: dmdl
          in: query
          description: Device model
          required: false
          type: string
        - name: fwver
          in: query
          description: Device firmware version
          required: false
          type: string
        - name: format
          in: query
          description: data decoding format
          required: true
          type: string
          enum:
            - HEX
            - BASE64
        - name: contentType
          in: query
          description: content type, ex image/png
          required: true
          type: string
        - name: properties
          in: query
          description: extra properties for decoding
          required: false
          type: string
        - name: data
          in: body
          description: content text
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/PushResult"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
definitions:
  ApiError: 
    type: "object"
    required: 
      - "code"
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
  MessageHeader:
    type: object
    properties:
      dkey:
        type: string
        description: domain key
      akey:
        type: string
        description: domain api-key
      did:
        type: string
        description: device id
      dmdl:
        type: string
        description: device model
      fwver:
        type: string
        description: device firmware version
      mid:
        type: string
        description: message identifier
    required:
      - key
      - api
      - did
      - dmdl
      - fwver
      - mid
  PushMessage:
    type: object
    properties:
      header:
        $ref: '#/definitions/MessageHeader'
      data:
        type: object
        description: message payload JSON object
    required:
      - header
      - data
  PushResult:
    type: object
    required:
      - muid
    properties:
      muid:
        type: string
        description: message unique identifier
