swagger: "2.0"
basePath: /api
schemes: 
  - http
  - https
produces: 
  - "application/json"
info: 
  version: "3.0.0-alpha1"
  title: "Boodskap API"
  description: "Boodskap IoT Platform API"
  termsOfService: "https://boodskap.io/terms-conditions"
  contact: 
    name: "Boodskap Team"
  license: 
    name: "MIT"
paths:
  '/asset/group/member/add/{oaid}/{gid}/{aid}':
    get:
      tags:
        - Add Asset Group Member
      summary: Add Asset Group Member
      operationId: addAssetGroupMember
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: oaid
          in: path
          description: Owner Asset ID
          required: true
          type: string
        - name: gid
          in: path
          description: Group ID
          required: true
          type: string
        - name: aid
          in: path
          description: Member Asset ID
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/asset/group/member/get/{oaid}/{gid}/{aid}':
    get:
      tags:
        - Get Asset Group Member
      summary: Get Asset Group Member
      operationId: getAssetGroupMember
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: oaid
          in: path
          description: Owner Asset ID
          required: true
          type: string
        - name: gid
          in: path
          description: Group ID
          required: true
          type: string
        - name: aid
          in: path
          description: Member Asset ID
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/AssetGroupMember'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/asset/group/member/count/{oaid}/{gid}':
    get:
      tags:
        - Count Asset Group Members
      summary: Count Asset Group Members
      operationId: countAssetGroupMembers
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: oaid
          in: path
          description: Owner Asset ID
          required: true
          type: string
        - name: gid
          in: path
          description: Group ID
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Count"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/asset/group/member/remove/{oaid}/{gid}':
    delete:
      tags:
        - Remove Asset Group Members
      summary: Remove Asset Group Members
      operationId: removeAssetGroupMembers
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: oaid
          in: path
          description: Owner Asset ID
          required: true
          type: string
        - name: gid
          in: path
          description: Group ID
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Success'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/asset/group/member/remove/{oaid}/{gid}/{aid}':
    delete:
      tags:
        - Remove Asset Group Member
      summary: Remove Asset Group Member
      operationId: removeAssetGroupMember
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: oaid
          in: path
          description: Owner Asset ID
          required: true
          type: string
        - name: gid
          in: path
          description: Group ID
          required: true
          type: string
        - name: aid
          in: path
          description: Member Asset ID
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Success'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/asset/group/member/list/{oaid}/{gid}':
    get:
      tags:
        - List Asset Group Members
      summary: List Asset Group Members
      operationId: listAssetGroupMembers
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: oaid
          in: path
          description: Owner Asset ID
          required: true
          type: string
        - name: gid
          in: path
          description: Group ID
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
        - name: page
          in: query
          description: Page index, starts from 0
          required: false
          type: integer
          format: int32
        - name: pageSize
          in: query
          description: Maximum number of assets to be listed
          required: false
          type: integer
          format: int32
        - name: next
          in: query
          description: If next is true, **eid** is required
          required: false
          type: boolean
        - name: aid
          in: query
          description: Last Member Asset Id of the previous list operation, **required** if **next** is true
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/AssetGroupMember'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/asset/group/member/search':
    post:
      tags:
        - Search Asset Group Members
      summary: Search Asset Group Members
      operationId: searchAssetGroupMembers
      consumes:
        - "application/json"
      produces:
        - application/json
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
        - name: pageSize
          in: query
          description: Maximum number of objects to be listed
          required: false
          type: integer
          format: int32
        - name: query
          in: body
          description: Search string
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/AssetGroupMember'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
definitions:
  ApiError: 
    type: "object"
    required: 
      - "code"
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
  AssetGroupMember:
    type: object
    required:
      - ownerAssetId
      - groupId
      - memberId
    properties:
      ownerAssetId:
        type: string
      groupId:
        type: string
      memberId:
        type: string
      domainKey:
        type: string
      registeredStamp:
        type: integer
        format: int64
  Count:
    type: object
    required:
      - total
    properties:
      total:
        type: integer
        format: int64
  DomainObject:
    type: object
    discriminator: domainObjectType
    properties:
      domainKey:
        type: string
  Property:
    allOf:
    - $ref: '#/definitions/SystemProperty'
    - $ref: '#/definitions/DomainObject'
    - type: object
      discriminator: propertyType
  Storable:
    type: object
    discriminator: storableType
    properties:
      dataFormat:
        type: string
        description: Required if **dataType** is **blob**
        enum:
          - AS_IS
          - JSON
          - HEX
          - BASE64
      description:
        type: string
  Success: 
    type: "object"
    required:
      - code
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
  SystemProperty:
    allOf:
    - $ref: '#/definitions/Storable'
    - type: object
      discriminator: systemPropertyType
      properties:
        name:
          type: string
        value:
          type: string
        createdStamp:
          type: integer
          format: int64
        updatedStamp:
          type: integer
          format: int64
