swagger: "2.0"
basePath: /api
schemes: 
  - http
  - https
produces: 
  - "application/json"
info: 
  version: "3.0.0-alpha1"
  title: "Boodskap API"
  description: "Boodskap IoT Platform API"
  termsOfService: "https://boodskap.io/terms-conditions"
  contact: 
    name: "Boodskap Team"
  license: 
    name: "MIT"
paths:
  '/drules/upsert':
    post:
      tags:
        - Upsert Domain Rule
      summary: Create / Update Domain Rule
      operationId: upsertDomainRule
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: entity
          in: body
          description: DomainRule JSON object
          required: true
          schema:
            $ref: '#/definitions/DomainRule'
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/drules/get':
    get:
      tags:
        - Get Domain Rule
      summary: Retreive Domain Rule
      operationId: getDomainRule
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/DomainRule'
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/drules/delete':
    delete:
      tags:
        - Delete Domain Rule
      summary: Delete Domain Rule
      operationId: deleteDomainRule
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/drules/count/all':
    get:
      tags:
        - Count All Domain Rules
      summary: Count All Domain Rules
      operationId: countAllDomainRules
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: atoken
          in: query
          description: Auth token of the logged in admin user
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Count"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
  '/drules/invoke/{messageId}':
    get:
      tags:
        - Invoke a Domain Rule
      summary: Invoke a Domain Rule
      operationId: invokeDomainRule
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: messageId
          in: path
          description: Message ID
          required: true
          type: string
        - name: atoken
          in: query
          description: Auth token of the logged in user
          required: true
          type: string
        - name: dkey
          in: query
          description: Domain Key, optional
          required: false
          type: string
      responses:
        '200':
          description: successful operation
          schema: 
            $ref: "#/definitions/Success"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
definitions:
  ApiError: 
    type: "object"
    required: 
      - "code"
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
  Count:
    type: object
    required:
      - total
    properties:
      total:
        type: integer
        format: int64
  DomainRule:
    allOf:
    - $ref: '#/definitions/Rule'
    - type: object
      required:
       - 'language'
       - 'code'
  Rule:
    type: object
    discriminator: ruleType
    required:
    - language
    - code
    properties:
      domainKey:
        type: string
      language:
        type: string
        enum:
          - GROOVY
          - JAVA_SCRIPT
          - NODE_JS
      code:
        type: string
      compilable:
        type: boolean
      loader:
        type: string
      globalLoader:
        type: string
      description:
        type: string
      contexts:
        type: array
        items:
          type: string
      plugins:
        type: array
        items:
          type: string
      createdStamp:
        type: integer
        format: int64
      updatedStamp:
        type: integer
        format: int64
        
  Success: 
    type: "object"
    required:
      - code
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
