swagger: "2.0"
basePath: /api
schemes: 
  - http
  - https
produces: 
  - "application/json"
info: 
  version: "3.0.0-alpha1"
  title: "Boodskap API"
  description: "Boodskap IoT Platform API"
  termsOfService: "https://boodskap.io/terms-conditions"
  contact: 
    name: "Boodskap Team"
  license: 
    name: "MIT"
paths:
  /build:
    get:
      summary: Returns the platform build information
      responses:
        '200':    # status code
          description: Build object
          schema: 
            $ref: "#/definitions/Build"
        "417":
          description: "API Error"
          schema: 
            $ref: "#/definitions/ApiError"
definitions:
  ApiError: 
    type: "object"
    required: 
      - "code"
    properties: 
      code: 
        type: "string"
      message: 
        type: "string"
  Build:
    properties:
      version:
        type: string
      stamp:
        type: string
      storagePagable:
        type: boolean
      storageSearchable:
        type: boolean
      rawStoragePagable:
        type: boolean
      rawStorageSearchable:
        type: boolean
      dynamicStoragePagable:
        type: boolean
      dynamicStorageSearchable:
        type: boolean
